# Project information
site_name: Electrificat
site_url: https://joseporiolayats.github.io/#electrificat
site_description: Get the best electricity rate
site_author: Josep Oriol Ayats

# Repository
repo_url: https://github.com/joseporiolayats/electrificat
repo_name: joseporiolayats/electrificat
edit_uri: "" #disables edit button

# Configuration
theme:
  name: material

# Extensions
markdown_extensions:
  - admonition # alerts
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings

# Page tree
nav:
  - Home:
      - My Project: index.md
  - Getting started: getting_started.md
  - Application:
      - API: app/api.md
      - Schemas: app/schemas.md
  - Operations: electrificat/main.md
  - Configurations: config/config.md
  - Reference:
      - Data: electrificat/data.md
      - Eval: electrificat/eval.md
#      - Models: electrificat/models.md
#      - Training: electrificat/train.md
#      - Inference: electrificat/predict.md
#      - Utilities: electrificat/utils.md
